language: go
go:
  - 1.11.x
before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/go:$GOPATH"
  - curl -Lo dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x dep && sudo mv dep /usr/local/bin/
install:
  - cd ${TRAVIS_BUILD_DIR}/go/src/kthw
  - make deps
script:
  - make all
