apiVersion: v1
kind: Service
metadata:
  name: simple-http-svc-nodeport
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 30000
    nodePort: 30002
  selector:
    app: simple-http-svc
---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: simple-http-svc
  labels:
    app: simple-http-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-http-svc
  template:
    metadata:
      labels:
        app: simple-http-svc
    spec:
      containers:
      - image: simple-http:current
        name: simple-http
        ports:
        - containerPort: 30000
          protocol: TCP

