apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-http-config
data:
  database.jdbc.url: jdbc://database/users?ssl=true
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-http-config
  labels:
    app: simple-http-config
spec:
  containers:
  - image: simple-http:current
    name: simple-http
    ports:
    - containerPort: 30000
      protocol: TCP
    env:
    - name: JDBC_URL
      valueFrom:
        configMapKeyRef:
          name: simple-http-config
          key: database.jdbc.url

